### PR TITLE
Support for UID, GID and home directory for containers

### PR DESCRIPTION
**Pull request by aicampbell**

### CODE REVIEW

**Comment by aicampbell** [comment]
closes #33 
closes #29

**Comment by acampsm** [comment]
We could use something like DYNAMIC_EXPERIMENTS_DATA_RETRIEVAL_ENDPOINT (used to retrieve experiments dynamically )  to call our private service to obtain uid, gid from a user/experiment or /user

**Comment by aicampbell** [comment]
Then you can add that inside the method.
We explicitly do not want to link containers with experiments.
But the method you write will be different for everyone else.

**Comment by acampsm** [comment]
If we add our code in the method, we will get conflicts with git. Should be better a dynamic call that retrieve this info. Like the others.
Each facility could have his own API with a endpoint defined in settings and all of them retrieve the uid and gid.

**Comment by aicampbell** [comment]
I agree it should be a dynamic call but we don't know how everyone else will implement these details. But these methods must not be added to Git as some are likely sensitive and the JSON response would be different too so you will break other people's code

**Comment by acampsm** [comment]
The result json must be the same skeleton the data would be different.

**Comment by aicampbell** [comment]
So can we accept this pull request and we can then change the method to to accept a configurable endpoint?

**Comment by acampsm** [comment]
Sorry Aidan, I had assume that it was not complete so it needs to implement an external endpoint to get the uid,gid from a username. I see /services/user.py (CalipsoUserServices class) and It seems correct but I am changing the resource_docker.py to accept both solutions. (One from username, and the other from experiment). Are you agree?

**Comment by aicampbell** [comment]
I don't agree with the experiment as there are a lot of things that could go wrong.

1) What happens if you have permission to see the experiment but you didn't participate in it?
That would probably break the UID and GID as those will not be your UID and GID. You are then accessing the data and starting a container under a different user.

2) What happens if you have multiple people involved in an experiment?
You will have 2 sets of UIDs and GIDs. Which one do you use? Which do you store in the database?

There are probably a lot more scenarios we need to consider...

**Comment by aicampbell** [comment]
If we do it with the user, they will always have the correct UID and GID. Also we shouldn't be storing these details in the database, we can make REST API calls as the data is so small.

**Comment by acampsm** [comment]
> If we do it with the user, they will always have the correct UID and GID. Also we shouldn't be storing these details in the database, we can make REST API calls as the data is so small.

I am agree with that. We could use the RESTAPI to get de UID,GID from a username inside the UserService class

**Comment by aicampbell** [comment]
I'm not at work this afternoon but if you accept the PR, it won't be hard to add the REST API call on Monday

**Comment by dsanchez-cells** [comment]
Okay, just so we are all in the same page. 

We agree in principle with the changes you propose, but there's still the matter of those facilities that don't use personal accounts to handle the access to the storage (the case of ALBA and, as far as I know, Elettra).

So, this PR works in the direction of addressing the concerns of the sites with personal accounts, but we still need to address that other use case. I believe we can make both systems work; say, if there's no endpoint defined in the settings, try to retrieve them from the database, or something like this. There are many ways to work this issue, but we do have to support both use cases if this is going to work for all sites involved.

Let us know what you think.

**Comment by aicampbell** [comment]
Yes, we need to support both cases.

But I'm afraid of adding UID and GID to the experiment model as we are making it more complicated and difficult to change in the future for such a small amount of data. I think its better to get them from another source e.g REST API. You can do this for both the experiments and the users. 

If you don't have a personal account, I assume you still have some way of getting the UID and GID from the experiment with an API right?

**Comment by dsanchez-cells** [comment]
Yes, I said database as an example, but we do get it from a REST API in the end. We had gone ahead and integrated it with the experiments endpoint, but we can certainly accept a separate endpoint for that. I agree entirely on the need to limit complexity in the model. Let's discuss this further on Monday.

We approve this PR now as a first step and we can look at the additional changes required next week.

**Review by dsanchez-cells — APPROVED** [review]

**Pull request merged**
